import { defineConfig } from 'tsup';

export default defineConfig({
  tsconfig: 'tsconfig.build.json',
  entry: {
    index: 'src/index.ts',
    preload: 'src/preload.ts',
    integrations: 'src/integrations.ts',
    menus: 'src/menus.ts',
    appkit: 'src/appkit.ts',
    lifecycle: 'src/lifecycle.ts',
    plugins: 'src/plugins.ts',
    'plugins/window-state': 'src/plugins/window-state.ts',
    'plugins/diagnostics': 'src/plugins/diagnostics.ts',
    'plugins/updater': 'src/plugins/updater.ts',
    boundary: 'src/boundary.ts',
    'adapters/assemblyscript': 'src/adapters/assemblyscript.ts',
    'adapters/loader': 'src/adapters/loader.ts',
    'adapters/named-pipe': 'src/adapters/named-pipe.ts',
    'adapters/grpc': 'src/adapters/grpc.ts',
    'adapters/stdio': 'src/adapters/stdio.ts',
    transport: 'src/transport.ts',
  },
  format: ['esm', 'cjs'],
  outExtension: ({ format }) => ({ js: format === 'esm' ? '.mjs' : '.cjs' }),
  dts: true,
  clean: true,
  sourcemap: true,
  splitting: false,
  treeshake: true,
  // electron and optional adapter packages are always externals — never bundle them
  external: [
    'electron',
    '@ozymandros/electron-message-bridge-adapter-assemblyscript',
    '@electron-ipc-helper/adapter-named-pipe',
    '@electron-ipc-helper/adapter-grpc',
    '@electron-ipc-helper/adapter-stdio',
    '@grpc/grpc-js',
  ],
  });